spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system3_ysh_car?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ysh0307
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath*:/mapper/*.xml